=== hwinkler/SegyRest/SegyServlet/sample/traces.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSPY v5 rel. 4 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
	xmlns:xlink="http://www.w3.org/1999/xlink" 
	xmlns:xml="http://www.w3.org/XML/1998/namespace"
>
 <xs:import namespace="http://www.w3.org/1999/xlink" schemaLocation="http://www.oasis-open.org/committees/ebxml-msg/schema/xlink.xsd" /> 
<xs:import namespace="http://www.w3.org/XML/1998/namespace"  schemaLocation="http://www.w3.org/2001/xml.xsd"/>
	<xs:element name="trace">
		<xs:complexType>
		  <xs:attribute ref="xlink:type" fixed="simple" /> 
 		 <xs:attribute ref="xlink:href" use="required" /> 
		</xs:complexType>
	</xs:element>
	<xs:element name="traces">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="trace" ref="trace" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute ref="xml:base"  use="optional"/> 
		</xs:complexType>
	</xs:element>
</xs:schema>

=== hwinkler/SegyRest/SegyServlet/sample/traces.xml
<?xml version="1.0" encoding="UTF-8"?>
<traces xml:base="http://localhost:8080/segy/segy/stratton/stratton.sgy/trace/" xmlns:xlink="http://www.w3.org/1999/xlink"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Documents and Settings\Hugh\Projects\SegyRest\SegyServlet\sample\traces.xsd">
	<trace xlink:type="simple" xlink:href="401"/>
	<trace xlink:type="simple" xlink:href="402"/>
	<trace xlink:type="simple" xlink:href="403"/>
	<trace xlink:type="simple" xlink:href="404"/>
	<trace xlink:type="simple" xlink:href="405"/>
	<trace xlink:type="simple" xlink:href="406"/>
	<trace xlink:type="simple" xlink:href="407"/>
	<trace xlink:type="simple" xlink:href="408"/>
	<trace xlink:type="simple" xlink:href="409"/>
	<trace xlink:type="simple" xlink:href="410"/>
	<trace xlink:type="simple" xlink:href="411"/>
	<trace xlink:type="simple" xlink:href="412"/>
	<trace xlink:type="simple" xlink:href="413"/>
	<trace xlink:type="simple" xlink:href="414"/>
	<trace xlink:type="simple" xlink:href="415"/>
	<trace xlink:type="simple" xlink:href="416"/>
	<trace xlink:type="simple" xlink:href="417"/>
	<trace xlink:type="simple" xlink:href="418"/>
	<trace xlink:type="simple" xlink:href="419"/>
	<trace xlink:type="simple" xlink:href="420"/>
	<trace xlink:type="simple" xlink:href="421"/>
	<trace xlink:type="simple" xlink:href="422"/>
	<trace xlink:type="simple" xlink:href="423"/>
	<trace xlink:type="simple" xlink:href="424"/>
	<trace xlink:type="simple" xlink:href="425"/>
	<trace xlink:type="simple" xlink:href="426"/>
	<trace xlink:type="simple" xlink:href="427"/>
	<trace xlink:type="simple" xlink:href="428"/>
	<trace xlink:type="simple" xlink:href="429"/>
	<trace xlink:type="simple" xlink:href="430"/>
	<trace xlink:type="simple" xlink:href="431"/>
	<trace xlink:type="simple" xlink:href="432"/>
	<trace xlink:type="simple" xlink:href="433"/>
	<trace xlink:type="simple" xlink:href="434"/>
	<trace xlink:type="simple" xlink:href="435"/>
	<trace xlink:type="simple" xlink:href="436"/>
	<trace xlink:type="simple" xlink:href="437"/>
	<trace xlink:type="simple" xlink:href="438"/>
	<trace xlink:type="simple" xlink:href="439"/>
	<trace xlink:type="simple" xlink:href="440"/>
	<trace xlink:type="simple" xlink:href="441"/>
	<trace xlink:type="simple" xlink:href="442"/>
	<trace xlink:type="simple" xlink:href="443"/>
	<trace xlink:type="simple" xlink:href="444"/>
	<trace xlink:type="simple" xlink:href="445"/>
	<trace xlink:type="simple" xlink:href="446"/>
	<trace xlink:type="simple" xlink:href="447"/>
	<trace xlink:type="simple" xlink:href="448"/>
	<trace xlink:type="simple" xlink:href="449"/>
	<trace xlink:type="simple" xlink:href="450"/>
	<trace xlink:type="simple" xlink:href="451"/>
	<trace xlink:type="simple" xlink:href="452"/>
	<trace xlink:type="simple" xlink:href="453"/>
	<trace xlink:type="simple" xlink:href="454"/>
	<trace xlink:type="simple" xlink:href="455"/>
	<trace xlink:type="simple" xlink:href="456"/>
	<trace xlink:type="simple" xlink:href="457"/>
	<trace xlink:type="simple" xlink:href="458"/>
	<trace xlink:type="simple" xlink:href="459"/>
	<trace xlink:type="simple" xlink:href="460"/>
	<trace xlink:type="simple" xlink:href="461"/>
	<trace xlink:type="simple" xlink:href="462"/>
	<trace xlink:type="simple" xlink:href="463"/>
	<trace xlink:type="simple" xlink:href="464"/>
	<trace xlink:type="simple" xlink:href="465"/>
	<trace xlink:type="simple" xlink:href="466"/>
	<trace xlink:type="simple" xlink:href="467"/>
	<trace xlink:type="simple" xlink:href="468"/>
	<trace xlink:type="simple" xlink:href="469"/>
	<trace xlink:type="simple" xlink:href="470"/>
	<trace xlink:type="simple" xlink:href="471"/>
	<trace xlink:type="simple" xlink:href="472"/>
	<trace xlink:type="simple" xlink:href="473"/>
	<trace xlink:type="simple" xlink:href="474"/>
	<trace xlink:type="simple" xlink:href="475"/>
	<trace xlink:type="simple" xlink:href="476"/>
	<trace xlink:type="simple" xlink:href="477"/>
	<trace xlink:type="simple" xlink:href="478"/>
	<trace xlink:type="simple" xlink:href="479"/>
	<trace xlink:type="simple" xlink:href="480"/>
	<trace xlink:type="simple" xlink:href="481"/>
	<trace xlink:type="simple" xlink:href="482"/>
	<trace xlink:type="simple" xlink:href="483"/>
	<trace xlink:type="simple" xlink:href="484"/>
	<trace xlink:type="simple" xlink:href="485"/>
	<trace xlink:type="simple" xlink:href="486"/>
	<trace xlink:type="simple" xlink:href="487"/>
	<trace xlink:type="simple" xlink:href="488"/>
	<trace xlink:type="simple" xlink:href="489"/>
	<trace xlink:type="simple" xlink:href="490"/>
	<trace xlink:type="simple" xlink:href="491"/>
	<trace xlink:type="simple" xlink:href="492"/>
	<trace xlink:type="simple" xlink:href="493"/>
	<trace xlink:type="simple" xlink:href="494"/>
	<trace xlink:type="simple" xlink:href="495"/>
	<trace xlink:type="simple" xlink:href="496"/>
	<trace xlink:type="simple" xlink:href="497"/>
	<trace xlink:type="simple" xlink:href="498"/>
	<trace xlink:type="simple" xlink:href="499"/>
	<trace xlink:type="simple" xlink:href="500"/>
	<trace xlink:type="simple" xlink:href="501"/>
	<trace xlink:type="simple" xlink:href="502"/>
	<trace xlink:type="simple" xlink:href="503"/>
	<trace xlink:type="simple" xlink:href="504"/>
	<trace xlink:type="simple" xlink:href="505"/>
	<trace xlink:type="simple" xlink:href="506"/>
	<trace xlink:type="simple" xlink:href="507"/>
	<trace xlink:type="simple" xlink:href="508"/>
	<trace xlink:type="simple" xlink:href="509"/>
	<trace xlink:type="simple" xlink:href="510"/>
	<trace xlink:type="simple" xlink:href="511"/>
	<trace xlink:type="simple" xlink:href="512"/>
	<trace xlink:type="simple" xlink:href="513"/>
	<trace xlink:type="simple" xlink:href="514"/>
	<trace xlink:type="simple" xlink:href="515"/>
	<trace xlink:type="simple" xlink:href="516"/>
	<trace xlink:type="simple" xlink:href="517"/>
	<trace xlink:type="simple" xlink:href="518"/>
	<trace xlink:type="simple" xlink:href="519"/>
	<trace xlink:type="simple" xlink:href="520"/>
	<trace xlink:type="simple" xlink:href="521"/>
	<trace xlink:type="simple" xlink:href="522"/>
	<trace xlink:type="simple" xlink:href="523"/>
	<trace xlink:type="simple" xlink:href="524"/>
	<trace xlink:type="simple" xlink:href="525"/>
	<trace xlink:type="simple" xlink:href="526"/>
	<trace xlink:type="simple" xlink:href="527"/>
	<trace xlink:type="simple" xlink:href="528"/>
	<trace xlink:type="simple" xlink:href="529"/>
	<trace xlink:type="simple" xlink:href="530"/>
	<trace xlink:type="simple" xlink:href="531"/>
	<trace xlink:type="simple" xlink:href="532"/>
	<trace xlink:type="simple" xlink:href="533"/>
	<trace xlink:type="simple" xlink:href="534"/>
	<trace xlink:type="simple" xlink:href="535"/>
	<trace xlink:type="simple" xlink:href="536"/>
	<trace xlink:type="simple" xlink:href="537"/>
	<trace xlink:type="simple" xlink:href="538"/>
	<trace xlink:type="simple" xlink:href="539"/>
	<trace xlink:type="simple" xlink:href="540"/>
	<trace xlink:type="simple" xlink:href="541"/>
	<trace xlink:type="simple" xlink:href="542"/>
	<trace xlink:type="simple" xlink:href="543"/>
	<trace xlink:type="simple" xlink:href="544"/>
	<trace xlink:type="simple" xlink:href="545"/>
	<trace xlink:type="simple" xlink:href="546"/>
	<trace xlink:type="simple" xlink:href="547"/>
	<trace xlink:type="simple" xlink:href="548"/>
	<trace xlink:type="simple" xlink:href="549"/>
	<trace xlink:type="simple" xlink:href="550"/>
	<trace xlink:type="simple" xlink:href="551"/>
	<trace xlink:type="simple" xlink:href="552"/>
	<trace xlink:type="simple" xlink:href="553"/>
	<trace xlink:type="simple" xlink:href="554"/>
	<trace xlink:type="simple" xlink:href="555"/>
	<trace xlink:type="simple" xlink:href="556"/>
	<trace xlink:type="simple" xlink:href="557"/>
	<trace xlink:type="simple" xlink:href="558"/>
	<trace xlink:type="simple" xlink:href="559"/>
	<trace xlink:type="simple" xlink:href="560"/>
	<trace xlink:type="simple" xlink:href="561"/>
	<trace xlink:type="simple" xlink:href="562"/>
	<trace xlink:type="simple" xlink:href="563"/>
	<trace xlink:type="simple" xlink:href="564"/>
	<trace xlink:type="simple" xlink:href="565"/>
	<trace xlink:type="simple" xlink:href="566"/>
	<trace xlink:type="simple" xlink:href="567"/>
	<trace xlink:type="simple" xlink:href="568"/>
	<trace xlink:type="simple" xlink:href="569"/>
	<trace xlink:type="simple" xlink:href="570"/>
	<trace xlink:type="simple" xlink:href="571"/>
	<trace xlink:type="simple" xlink:href="572"/>
	<trace xlink:type="simple" xlink:href="573"/>
	<trace xlink:type="simple" xlink:href="574"/>
	<trace xlink:type="simple" xlink:href="575"/>
	<trace xlink:type="simple" xlink:href="576"/>
	<trace xlink:type="simple" xlink:href="577"/>
	<trace xlink:type="simple" xlink:href="578"/>
	<trace xlink:type="simple" xlink:href="579"/>
	<trace xlink:type="simple" xlink:href="580"/>
	<trace xlink:type="simple" xlink:href="581"/>
	<trace xlink:type="simple" xlink:href="582"/>
	<trace xlink:type="simple" xlink:href="583"/>
	<trace xlink:type="simple" xlink:href="584"/>
	<trace xlink:type="simple" xlink:href="585"/>
	<trace xlink:type="simple" xlink:href="586"/>
	<trace xlink:type="simple" xlink:href="587"/>
	<trace xlink:type="simple" xlink:href="588"/>
	<trace xlink:type="simple" xlink:href="589"/>
	<trace xlink:type="simple" xlink:href="590"/>
	<trace xlink:type="simple" xlink:href="591"/>
	<trace xlink:type="simple" xlink:href="592"/>
	<trace xlink:type="simple" xlink:href="593"/>
	<trace xlink:type="simple" xlink:href="594"/>
	<trace xlink:type="simple" xlink:href="595"/>
	<trace xlink:type="simple" xlink:href="596"/>
	<trace xlink:type="simple" xlink:href="597"/>
	<trace xlink:type="simple" xlink:href="598"/>
	<trace xlink:type="simple" xlink:href="599"/>
	<trace xlink:type="simple" xlink:href="600"/>
</traces>
